apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      annotations:
        configmap.nginx: 'nginx-config-v1'
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: vite-with-docker
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: VITE_PUBLIC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: VITE_PUBLIC_CLIENT_SECRET
            - name: VITE_PUBLIC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: VITE_PUBLIC_CLIENT_ID
            - name: VITE_BACK_API
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: VITE_BACK_API
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          resources:
            limits:
              cpu: '500m'
              memory: '512Mi'
            requests:
              cpu: '250m'
              memory: '256Mi'
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
