apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }

    http {
      limit_req_zone $binary_remote_addr zone=one:10m rate=10r/s;
      limit_conn_zone $binary_remote_addr zone=addr:10m;

      gzip on;
      gzip_types text/plain application/json application/javascript text/css;
      gzip_min_length 1000;

      include /etc/nginx/mime.types;
      default_type application/octet-stream;

      sendfile on;
      keepalive_timeout 65;

      include /etc/nginx/conf.d/*.conf;
    }

  default.conf: |
    server {
      listen 80;
      server_name localhost;

      root /usr/share/nginx/html;
      index index.html index.htm;

      location / {
        limit_req zone=one burst=20 nodelay;
        limit_conn addr 10;

        try_files $uri $uri/ /index.html;
      }
    }
